apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sistema-emails
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "TROQUE_AQUI"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=TROQUE_AQUI;Ssl Mode=Disable"
